[project]
name = "fde-happyrobbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.128.8",
    "ngrok>=1.4.0",
    "psycopg2-binary>=2.9.11",
    "sqlmodel>=0.0.33",
    "uvicorn>=0.39.0",
]
